name: chatapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  dash_chat_2: ^0.0.21
  firebase_analytics: ^11.3.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  flutter_login: ^5.0.0
  loading_animation_widget: ^1.3.0
  adaptive_theme: ^3.7.0
  provider: ^6.1.2
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.4.1
  file_picker: ^8.1.7
  flutter_lints: ^5.0.0
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/talkflow_icon.png
    - assets/images/logo.png