// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtDQDAaPUQ8wcUwO--_dMBOsNjTiIDZns',
    appId: '1:1081067066927:web:3197c05dfb6fd769f318da',
    messagingSenderId: '1081067066927',
    projectId: 'diary1915-878fd',
    authDomain: 'diary1915-878fd.firebaseapp.com',
    databaseURL: 'https://diary1915-878fd-default-rtdb.firebaseio.com',
    storageBucket: 'diary1915-878fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIKm7rmwCwvvfpjLePBbNFWcPp09O9_I4',
    appId: '1:1081067066927:android:77bcca54c751f22bf318da',
    messagingSenderId: '1081067066927',
    projectId: 'diary1915-878fd',
    databaseURL: 'https://diary1915-878fd-default-rtdb.firebaseio.com',
    storageBucket: 'diary1915-878fd.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtDQDAaPUQ8wcUwO--_dMBOsNjTiIDZns',
    appId: '1:1081067066927:web:da17de70f622a90af318da',
    messagingSenderId: '1081067066927',
    projectId: 'diary1915-878fd',
    authDomain: 'diary1915-878fd.firebaseapp.com',
    databaseURL: 'https://diary1915-878fd-default-rtdb.firebaseio.com',
    storageBucket: 'diary1915-878fd.appspot.com',
  );

}